title: Java para principiantes
description: Humilde guía para comenzar a desarrollar aplicaciones de consola en Java sin muchos problemas
lang: es
google_analytics:
google_gtm: G-01M2272H7P

plugins:
  - jekyll-seo-tag
